services:
  - type: web
    name: bulkloader-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 -m Bot"
    plan: free
    envVars:
      - key: APP_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false